---
title: "Library Corner"
format: html
---

## Monument Management
-   2024- [Lalo (French Frigate Shoals) Resilience Implementation Options Report : Report To The Papahānaumokuākea Marine National Monument Management Board](https://repository.library.noaa.gov/view/noaa/56798){.external target="_blank"}
-   2023.09- [Mai Ka Pō Mai: applying Indigenous cosmology and worldview to empower and transform a management plan for Papahānaumokuākea Marine National Monument](https://repository.library.noaa.gov/view/noaa/60954){.external target="_blank"}
-   2018.11.13- [Incorporating Nature and Culture into the Daily Management of Papahānaumokuākea Marine National Monument](https://usicomos.org/wp-content/uploads/2019/11/Clark-_-Miller-2019-US-ICOMOS-Proceedings.pdf){.external target="_blank"}
-   2014 [Environmental assessment, Papahānaumokuākea Marine National Monument, Northwestern Hawaiian Islands Hawai'i](https://repository.library.noaa.gov/view/noaa/10210/){.external target="_blank"}

## Monk Seals
-   2023- [In the face of sea level rise, NOAA helps endangered Hawaiian monk seals find higher ground](https://www.climate.gov/news-features/features/face-sea-level-rise-noaa-helps-endangered-hawaiian-monk-seals-find-higher){.external target="_blank"}
-   2023- [Monitoring the diurnal and seasonal foraging of Hawaiian monk seals in mesophotic rubble habitat using seafloor event loggers called ‘electric rocks’](https://repository.library.noaa.gov/view/noaa/58463){.external target="_blank"}
-   2016- [Preliminary assessment of monk seal-fishery interactions in the Main Hawaiian Islands](https://repository.library.noaa.gov/view/noaa/12968){.external target="_blank"}
-   2009.03- [Clinical observations of ocular disease in Hawaiian monk seals (Monachus schauinslandi)](https://repository.library.noaa.gov/view/noaa/4171){.external target="_blank"}
-   2008.01.08- [Shark predation on Hawaiian monk seals workshop, Honolulu, Hawaii, January 8-9, 2008](https://repository.library.noaa.gov/view/noaa/21424){.external target="_blank"}

## Sea Turtles
-   2025- [Marine debris impacts on Hawaiian green sea turtles (Chelonia mydas): High prevalence of hook-and-line fishing gear in strandings](https://www.sciencedirect.com/science/article/pii/S0025326X25003443){.external target="_blank"}
-   2024  [Abundance, production, and migrations of nesting green turtles at Rose Atoll, American Samoa, a regionally important rookery in the Central South Pacific Ocean](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2024.1403240/full){.external target="_blank"}
-   2024- [Sex ratios of olive ridley sea turtles in the North Pacific high seas: implications for climate change research](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.int-res.com/articles/meps_oa/m748p149.pdf){.external target="_blank"}
-   2023- [Population structure of Pacific green turtles: a new perspective from microsatellite DNA variation](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2023.1116941/full){.external target="_blank"}
-   2020- [Hawaiian hawksbills: a distinct and isolated nesting colony in the Central North Pacific Ocean revealed by mitochondrial DNA](https://link.springer.com/article/10.1007/s10592-020-01287-1){.external target="_blank"}
-   2020- [Sea turtle tagging in the Mariana Islands Training and Testing (MITT) study area](https://repository.library.noaa.gov/view/noaa/23886){.external target="_blank"}
-   2019- [Densities and drivers of sea turtle populations across Pacific coral reef ecosystems](https://repository.library.noaa.gov/view/noaa/24908){.external target="_blank"}
-   2018- [Environmental Warming and Feminization of One of the Largest Sea Turtle Populations in the World](https://www.cell.com/current-biology/fulltext/S0960-9822(17)31539-7?inline-read-more=){.external target="_blank"}

##  Project Reports
-   2023- [Project Report : NOAA Ship Oscar Elton Sette, SE-22-06](https://repository.library.noaa.gov/view/noaa/55664){.external target="_blank"}
-   2022- [Project Report: NOAA Ship Oscar Elton Sette, SE-21-04](https://repository.library.noaa.gov/view/noaa/47712){.external target="_blank"}
