---
title: "Worksite Training"
format: html
---

## B130 Orientation

-   [B130 Training Sheet](https://docs.google.com/document/d/1bXpfzask-ZBk4dFhgJK8Fyk_KqSVhMdWFC9cAmUgJmc/edit?usp=drive_link){.external target="_blank"}
-   [B130 Operations and Safety Manual](https://docs.google.com/document/d/1pxLHU5h5ZJVFUV_oFnWiT6xChJVxrHu_1cKWpEbxP3M/edit?usp=drive_link){.external target="_blank"}
-   [B130 HAZCOM](https://docs.google.com/presentation/d/19Gjx0wf3lpIJbPrY_MM6rmala9A0BZICOpbgX_4YYZw/edit?usp=drive_link){.external target="_blank"}

## IRC Lab Training

A signed user agreement on file with the Lab Manager is required to become an authorized lab user. Complete the following:

1.   Review the [Laboratory Safety Briefing Slides (Version 6)](https://docs.google.com/presentation/d/1ey4m6rBtt3Dqd61iKIFp5CFH9tVJhUS9bB6FCj41IgA/edit#slide=id.g3226f387574_2_63){.external target="_blank"}.
2.   Take the Quiz at the end of the briefing.
3.   Review the [Biosafety Plan](https://sites.google.com/noaa.gov/pifsc-labs/bio-chem-labs/biosafety-plan){.external target="_blank"}.
4.   [Review the Chemical Hygiene Plan](https://sites.google.com/noaa.gov/pifsc-labs/bio-chem-labs/chp){.external target="_blank"}.
5.   Print out the [Lab User Agreement](https://docs.google.com/document/d/15EfBEdMe47GsK4E_0zkZLj9_dKu-xfRM8InxwbF-rQ8/edit?tab=t.0#heading=h.1302m92){.external target="_blank"}, which is Appendix C in the Chemical Hygiene Plan. Open in Adobe Acrobat and print the relevant two pages.
6.   Complete the checklist in the User Agreement.
7.   Schedule a Lab Safety Orientation with the Lab Manager.
8.   Obtain signatures and provide the signed form to the Lab Manager.
